WATCHLIST_STATES = {"READY", "WATCHING", "WEAK", "INVALID", "TRIGGERED", "EXPIRED"}
MARKET_STATES = {"WATCHING", "ACCUMULATING", "BREAKOUT_READY", "BREAKDOWN_READY", "PULLBACK_READY", "TRENDING", "CHOPPY", "WEAK", "INVALID"}
SCORE_WEIGHTS = {"confidence": 30, "quality": 20, "orderflow": 15, "volume": 10, "risk_reward": 10, "momentum": 10, "htf_context": 5}
QUALITY_THRESHOLD = 40

MARKET_STATE_TRANSITIONS = {
    "WATCHING": {"ACCUMULATING", "BREAKOUT_READY", "BREAKDOWN_READY", "PULLBACK_READY", "TRENDING", "CHOPPY", "WEAK", "INVALID"},
    "ACCUMULATING": {"BREAKOUT_READY", "WATCHING", "TRENDING", "WEAK"},
    "BREAKOUT_READY": {"TRENDING", "CHOPPY", "WEAK"},
    "BREAKDOWN_READY": {"TRENDING", "CHOPPY", "WEAK"},
    "PULLBACK_READY": {"TRENDING", "BREAKOUT_READY", "WATCHING", "WEAK"},
    "TRENDING": {"CHOPPY", "WEAK", "PULLBACK_READY"},
    "CHOPPY": {"WATCHING", "BREAKOUT_READY", "BREAKDOWN_READY", "WEAK"},
    "WEAK": {"WATCHING", "INVALID"},
    "INVALID": set(),
}
